spring.application.name=notificaciones
server.port=${PORT:8082}
spring.data.mongodb.uri=${NOT_URI}

# CloudAMQP
spring.rabbitmq.addresses=${CLOUDAMQP_URL}

# URL de MicroUsuario (en Render apunta a la URL pública)
micro.usuario.url=${MICRO_USUARIO_URL}