spring.application.name=imagenes
server.port=8083

# MongoDB - URI COPIADA DEL .env
spring.data.mongodb.uri=mongodb+srv://user_mongo:fullstack3duoc@cluster0.3zqkci4.mongodb.net/db_fullstack?retryWrites=true&w=majority

# File upload configuration
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB
spring.servlet.multipart.enabled=true

# Logging
logging.level.com.proyect.imagenes=DEBUG
logging.level.org.springframework.data.mongodb=DEBUG

# Swagger
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.api-docs.path=/api-docs